import { Telegraf, Markup } from "telegraf";
import type { VercelRequest, VercelResponse } from "@vercel/node";
import { rggu, type ScheduleResponse } from "./rggu.js";
import { getUser, saveUser, type User } from "./store.js";

const bot = new Telegraf(process.env.BOT_TOKEN || "");
const menu = Markup.keyboard([["📅 Today", "📅 Tomorrow"], ["🗓 Week", "📆 Month"], ["⚙️ Setup", "👤 Profile"], ["🔔 Notifications", "❓ Help"]]).resize();
const profileMenu = Markup.inlineKeyboard([[Markup.button.callback("📝 Exams", "profile:exams"), Markup.button.callback("📊 Statistics", "profile:stats")], [Markup.button.callback("✅ Attendance", "profile:attendance"), Markup.button.callback("🔗 Useful links", "profile:links")], [Markup.button.callback("🔄 Refresh data", "profile:refresh")]);
async function user(ctx: any): Promise<User> { return (await getUser(ctx.from.id)) || { chatId: ctx.from.id, notifyTimes: ["07:00", "22:00"] }; }
function time(pair: number) { return ({1:"08:45–10:05",2:"10:15–11:35",3:"12:10–13:30",4:"13:40–15:00",5:"15:35–16:55",6:"17:05–18:25",7:"18:50–20:10",8:"20:20–21:40"} as Record<number,string>)[pair] || ""; }
function render(data: ScheduleResponse, title = "Schedule") { const lines = [`📅 ${title}`, data.item || "", data.interval ? `\n${data.interval}` : "", "──────────────────"]; for (const day of data.tblData || []) { lines.push(`📅 ${day.date}`); for (const p of day.pairs || []) for (const f of p.flows || []) { lines.push(`${p.pair} class  ${time(p.pair)}\n📌 ${f.subject}`); if (f.lessontype && f.lessontype !== "-") lines.push(`📚 ${f.lessontype}`); if (f.teacher_fullfio && f.teacher_fullfio !== "-") lines.push(`👤 ${f.teacher_fullfio}`); if (f.room && f.room !== "-") lines.push(`📍 ${f.room}`); } lines.push("\n──────────────────"); } lines.push(`Updated: ${data.updatetime || "unknown"}`); return lines.join("\n").slice(0, 3900); }
async function schedule(ctx: any, intervalMode: string, title: string) { const u = await user(ctx); if (!u.flow) return ctx.reply("Please choose your group first with ⚙️ Setup or /setup.", menu); const data = await rggu.schedule({ menuMode:"flow", flow:u.flow, eduform:u.eduform || "3", course:u.course || "1", intervalMode }); return ctx.reply(render(data, title), menu); }

bot.start(ctx => ctx.reply("Welcome to the English RGGU schedule bot!\n\nChoose your group once and I will show your classes, exam reminders, and notifications.", menu));
bot.command("help", ctx => ctx.reply("📅 Schedule\n/today — today\n/tomorrow — tomorrow\n/week — one week\n/month — 30 days\n\n🔍 Search\nWrite a subject name, or use: teacher <surname>\n\n⚙️ Settings\n/setup — change group\n/profile — profile, exams and progress\n/notify — notification times", menu));
bot.command("setup", async ctx => { const f = await rggu.forms(); return ctx.reply("Choose your study form 📋", Markup.inlineKeyboard(f.eduform.slice(0, 30).map(x => [Markup.button.callback(x.data, `form:${x.id}`)]))); });
bot.action(/^form:(.+)$/, async ctx => { await ctx.answerCbQuery(); const form = ctx.match[1]; const flows = await rggu.flows(form, "1"); const u = await user(ctx); await saveUser({ ...u, eduform: form, course: "1" }); return ctx.editMessageText("Choose your group:", Markup.inlineKeyboard(flows.slice(0, 80).map(x => [Markup.button.callback(x.data, `flow:${x.id}`)]))); });
bot.action(/^flow:(.+)$/, async ctx => { await ctx.answerCbQuery(); const u = await user(ctx); await saveUser({ ...u, flow: ctx.match[1], flowName: ctx.match[1] }); await ctx.editMessageText("Your group is saved ✅"); return ctx.reply("Setup complete. Use the menu below.", menu); });
bot.command("today", ctx => schedule(ctx, "1", "Today")); bot.command("tomorrow", ctx => schedule(ctx, "1", "Tomorrow")); bot.command("week", ctx => schedule(ctx, "2", "Schedule for one week")); bot.command("month", ctx => schedule(ctx, "3", "Schedule for 30 days"));
bot.hears("📅 Today", ctx => schedule(ctx, "1", "Today")); bot.hears("📅 Tomorrow", ctx => schedule(ctx, "1", "Tomorrow")); bot.hears("🗓 Week", ctx => schedule(ctx, "2", "Schedule for one week")); bot.hears("📆 Month", ctx => schedule(ctx, "3", "Schedule for 30 days")); bot.hears("⚙️ Setup", ctx => ctx.reply("Use /setup to choose your study form and group.")); bot.hears("❓ Help", ctx => ctx.reply("Use /help for all commands.", menu));
bot.command("profile", async ctx => { const u = await user(ctx); if (!u.flow) return ctx.reply("Please complete /setup first.", menu); const data = await rggu.schedule({ menuMode:"flow", flow:u.flow, eduform:u.eduform || "3", course:u.course || "1", intervalMode:"4" }); const total = (data.tblData || []).reduce((n,d) => n + d.pairs.length, 0); return ctx.reply(`👤 ${u.flowName || "Your group"}\n\n📝 Exams: checking schedule data\n📊 Scheduled classes in semester: ${total}`, profileMenu); });
bot.action(/^profile:(.+)$/, async ctx => { await ctx.answerCbQuery(); const type = ctx.match[1]; if (type === "attendance") return ctx.reply("✅ Attendance is available through the RGGU app.", menu); if (type === "links") return ctx.reply("🔗 Useful links\n🏛 RGGU: https://rsuh.ru/\n👤 Student portal: https://portal.rggu.ru/\n📚 Specialist courses: https://specialist.rggu.ru/course\n🎓 Mirapolis: https://elearn.rggu.ru/mira\n📞 Contacts: https://rsuh.ru/contacts/ucheb.php", menu); if (type === "exams") return ctx.reply("📝 Exams\nExam reminders will appear here when they are present in the RGGU data.", menu); if (type === "stats") return ctx.reply("📊 Statistics\nStatistics are calculated from your semester schedule.", menu); return ctx.reply("Profile data refreshed ✅", menu); });
function notifyKeyboard(times: string[]) { const has = (t:string) => times.includes(t) ? "✅ " : ""; return Markup.inlineKeyboard([["07:00","10:00","13:00"].map(t => Markup.button.callback(has(t)+t, `notify:${t}`)), ["16:00","19:00","22:00"].map(t => Markup.button.callback(has(t)+t, `notify:${t}`))], [Markup.button.callback("⏰ Custom time", "notify:custom"), Markup.button.callback("🔕 Disable", "notify:none")], [Markup.button.callback("💾 Save", "notify:save")]); }
bot.command("notify", async ctx => { const u = await user(ctx); return ctx.reply("When should I send your schedule? 🔔\n\nMorning: today’s schedule. Evening: tomorrow’s schedule.", notifyKeyboard(u.notifyTimes)); });
bot.action(/^notify:(.+)$/, async ctx => { await ctx.answerCbQuery(); const u = await user(ctx); const v = ctx.match[1]; if (/^\d\d:\d\d$/.test(v)) u.notifyTimes = u.notifyTimes.includes(v) ? u.notifyTimes.filter(x => x !== v) : [...u.notifyTimes, v]; if (v === "none") u.notifyTimes = []; if (v === "save") { await saveUser(u); return ctx.reply("Notification settings saved ✅", menu); } await saveUser(u); return ctx.editMessageReplyMarkup(notifyKeyboard(u.notifyTimes).reply_markup); });
bot.on("text", async ctx => { const text = ctx.message.text.trim(); if (text.startsWith("/")) return; const u = await user(ctx); if (!u.flow) return ctx.reply("Please choose your group first with /setup.", menu); if (/^(teacher|препод)\s+/i.test(text)) { const query = text.replace(/^(teacher|препод)\s+/i, ""); const teachers = await rggu.teachers(); const match = teachers.find(t => t.data.toLowerCase().includes(query.toLowerCase())); if (!match) return ctx.reply("I could not find that teacher.", menu); const data = await rggu.schedule({ menuMode:"teacher", teacher:match.id, intervalMode:"1" }); return ctx.reply(render(data, `👤 ${match.data}`), menu); } const data = await rggu.schedule({ menuMode:"flow", flow:u.flow, eduform:u.eduform || "3", course:u.course || "1", intervalMode:"3" }); const hits = (data.tblData || []).flatMap(d => d.pairs.flatMap(p => p.flows.filter(f => f.subject.toLowerCase().includes(text.toLowerCase())).map(f => ({ d, p, f })))); if (!hits.length) return ctx.reply("I could not find that subject in your schedule.", menu); const first = hits[0]; return ctx.reply(`🔍 Nearest class\n\n📅 ${first.d.date}\n${first.p.pair} class  ${time(first.p.pair)}\n📌 ${first.f.subject}\n👤 ${first.f.teacher_fullfio || "-"}\n📍 ${first.f.room || "-"}\n\n📚 Classes remaining: ${hits.length}`, menu); });
export default async function handler(req: VercelRequest, res: VercelResponse) { if (req.method === "GET") return res.status(200).json({ ok:true, service:"rggu-english-bot" }); if (!process.env.BOT_TOKEN) return res.status(500).json({ ok:false, error:"BOT_TOKEN is not configured" }); try { await bot.handleUpdate(req.body); return res.status(200).json({ ok:true }); } catch (e) { console.error(e); return res.status(500).json({ ok:false }); } }
